publish_mode: editorial_workflow
media_folder: src/assets/uploads
public_folder: /assets

collections:
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "src/content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "FrontImage", name: "frontimage", widget: "image"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Text", name: "text", widget: "markdown"}