backend:
  name: github
  repo: svirins/iam
  branch: main


media_folder: /src/assets/uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "page"
    label: "Page"
    folder: "/src/content/pages"
    create: true
    slug: "{{title}}" # this will be filename
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "FrontImage", name: "frontimage", widget: "image"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Text", name: "text", widget: "markdown"}

