backend:
  name: github
  repo: svirins/iam
  branch: main


media_folder: content/assets
public_folder: /assets


collections:
  - name: "page"
    label: "Page"
    folder: "content/pages"
    create: true
    slug: "{{title}}" 
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "FrontImage", name: "frontimage", widget: "image"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Text", name: "text", widget: "markdown"}

