backend:
  name: git-gateway
  branch: main



media_folder: static/img
public_folder: /img


collections:
  - name: "page"
    label: "Page"
    folder: "src/content"
    create: true
    slug: "{{title}}" 
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Price", name: "price", widget: "number", required: true}
      - {label: "SEO Title", name: "seoTitle", widget: "string"}
      - {label: "SEO Description", name: "seoDescription", widget: "string"}
      - {label: "Svg image (square)", name: "image", widget: "image"}
      - {label: "Text", name: "text", widget: "markdown", required: true}


